FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./

COPY . ./

RUN npm install
RUN npm run build

EXPOSE 3000
 
CMD ["npm", "start"]


FROM nginx:alpine

COPY ../nginx/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/build /usr/share/nginx/html

ENTRYPOINT ["nginx", "-g", "daemon off;"]