FROM python:3.9

WORKDIR /code

COPY ./backend/requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./backend/app /code/app

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0" "--port", "8080", "--reload"]
